import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Ticket System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="">Welcome to Ticket System.</h1>
      </main>
    </div>
  );
}
